//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ID { get; set; }
        public string OrderType { get; set; }
        public Nullable<bool> Import { get; set; }
        public string PickupStoreNumber { get; set; }
        public string PickupStoreName { get; set; }
        public Nullable<decimal> PickupLatitude { get; set; }
        public Nullable<decimal> PickupLongitude { get; set; }
        public string PickupFormattedAddress { get; set; }
        public string PickupContactFirstName { get; set; }
        public string PickupContactLastName { get; set; }
        public string PickupContactEmail { get; set; }
        public string PickupContactMobileNumber { get; set; }
        public Nullable<bool> PickupEnableSMSNotification { get; set; }
        public Nullable<System.TimeSpan> PickupTime { get; set; }
        public Nullable<int> PickupToleranceMinutes { get; set; }
        public Nullable<int> PickupServiceTime { get; set; }
        public string DeliveryStoreNumber { get; set; }
        public string DeliveryStoreName { get; set; }
        public Nullable<decimal> DeliveryLatitude { get; set; }
        public Nullable<decimal> DeliveryLongitude { get; set; }
        public string DeliveryFormattedAddress { get; set; }
        public string DeliveryContactFirstName { get; set; }
        public string DeliveryContactLastName { get; set; }
        public string DeliveryContactEmail { get; set; }
        public string DeliveryContactMobileNumber { get; set; }
        public Nullable<bool> DeliveryEnableSMSNotification { get; set; }
        public Nullable<System.TimeSpan> DeliveryTime { get; set; }
        public Nullable<int> DeliveryToleranceMinutes { get; set; }
        public Nullable<int> DeliveryServiceTimeMinutes { get; set; }
        public string OrderDetails { get; set; }
        public string AssignedDriver { get; set; }
        public string CustomerReference { get; set; }
        public string Payer { get; set; }
        public string Vehicle { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> Price { get; set; }
    }
}
